exclude_path = [
  "sources/incoming",
  "sources/processed",
]

exclude = [
  "^https?://(www\\.)?example\\.com(/.*)?$",
  "^https?://github\\.com/example(/.*)?$",
  "^https?://localhost(:[0-9]+)?(/.*)?$",
  "^http://localhost(:[0-9]+)?(/.*)?$",
  "^https?://127\\.0\\.0\\.1(:[0-9]+)?(/.*)?$",
  "^http://127\\.0\\.0\\.1(:[0-9]+)?(/.*)?$",
  "^https://github\\.com/David-A18/MY-humble-knowledge-for-everyone/actions/runs/[0-9]+.*$",
]
