name: Link check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config lychee.toml --root-dir "${{ github.workspace }}" --verbose --no-progress "**/*.md"
